# Site settings
title: 홍가뤼의 개인위키
url: "https://honggaruy.github.io"
baseurl: ""
description: >
    홍가리의 블로그

# My information
email: honggaruy@gmail.com
author: honggaruy
profile: 가득차기전에 움직인다 
twitter_username: null 
github_username: honggaruy
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: h0nggari@naver.com
  shortname: h0nggari
utterances:
  repo: honggaruy/honggaruy.github.io
  issue-term: pathname
  label: Comment
  theme: github-light # photon-dark, github-light
  crossorigin: anonymous

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/honggaruy/honggaruy.github.io/blame/master/_wiki"
edit: "https://github.com/honggaruy/honggaruy.github.io/edit/master/_wiki"
issue: "https://github.com/honggaruy/honggaruy.github.io/issues/new"

timezone: "Asia/Seoul"
